{{- if .Values.autoUpdate.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "qualys-ca.fullname" . }}-auto-update
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qualys-ca.labels" . | nindent 4 }}
    app.kubernetes.io/component: auto-update
rules:
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "patch", "update"]
- apiGroups: ["apps"]
  resources: ["daemonsets/status"]
  verbs: ["get"]
{{- end }}
