{{- if .Values.autoUpdate.enabled }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "qualys-ca.fullname" . }}-auto-update
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qualys-ca.labels" . | nindent 4 }}
    app.kubernetes.io/component: auto-update
subjects:
- kind: ServiceAccount
  name: {{ include "qualys-ca.fullname" . }}-auto-update
  namespace: {{ .Values.namespace.name }}
roleRef:
  kind: Role
  name: {{ include "qualys-ca.fullname" . }}-auto-update
  apiGroup: rbac.authorization.k8s.io
{{- end }}
