{{- if .Values.autoUpdate.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "qualys-ca.fullname" . }}-auto-update
  namespace: {{ .Values.namespace.name }}
  labels:
    {{- include "qualys-ca.labels" . | nindent 4 }}
    app.kubernetes.io/component: auto-update
{{- end }}
